// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllUsersUserCraetedAtAsc(ctx context.Context, arg GetAllUsersUserCraetedAtAscParams) ([]User, error)
	GetAllUsersUserCreatedAtDesc(ctx context.Context, arg GetAllUsersUserCreatedAtDescParams) ([]User, error)
	GetAllUsersUserIdAsc(ctx context.Context, arg GetAllUsersUserIdAscParams) ([]User, error)
	GetAllUsersUserIdDesc(ctx context.Context, arg GetAllUsersUserIdDescParams) ([]User, error)
	GetUserByEmail(ctx context.Context, userEmail string) (User, error)
	GetUserByUuid(ctx context.Context, userUuid uuid.UUID) (User, error)
	RestoreUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	SoftDeleteUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	TrashUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	UpdateUserByUuid(ctx context.Context, arg UpdateUserByUuidParams) (User, error)
}

var _ Querier = (*Queries)(nil)
